# frozen_string_literal: true

FactoryBot.define do
  factory :foodbank do
    fb_id { SecureRandom.rand(10_000) }
    fb_name { Faker::Company.name }
    fb_nickname { fb_name }
    fb_type_id { 1 }
    fb_logo { '' }
    display_order { 1 }
    invoicing_status { 0 }
    per_agency_rate { 0 }
    agency_contract_visibility_status { 0 }
    fb_contract_signing_status { 0 }
    macola_cus_no { 0 }
    number_of_pantries { 0 }
    number_of_other_grocery_agencies { 0 }
    nar_fy15_num_emergency_pantries { 0 }
    nar_fy15_num_produce_markets { 0 }
    nar_fy15_num_soup_kitchens { 0 }
    nar_fy15_num_emergency_shelters { 0 }
    nar_fy15_num_residential { 0 }
    nar_fy15_num_day_care { 0 }
    nar_fy15_num_seniors { 0 }
    nar_fy15_num_rehabilitation { 0 }
    nar_fy15_num_youth_programs { 0 }
    send(:'nar_fy15_num_multi-serv') { 0 }
    nar_fy15_num_csfp { 0 }
    nar_fy15_num_other { 0 }
    nar_fy15_total_served { 0 }
    nar_fy14_total_served { 0 }
    nar_fy15_other_desc { 0 }
    nar_fy15_ap_staf { 0 }
    fb_size { 0 }
    fb_contact_info { 0 }
    fb_help_info { 0 }
    primary_contact_id { 0 }
    admin_loc_id { 0 }
    contact_group_id { 0 }
    epg_2_group { 0 }
    implementation_status { 0 }
    implementation_narrative { 0 }
    implementation_anectdote { 0 }
    outreach_status { 0 }
    sale_status { 0 }
    opportunity_description { 0 }
    current_probability { 0 }
    value { 0 }
    value_fy18 { 0 }
    value_fy18_onetime { 0 }
    value_fy19 { 0 }
    value_fy19_onetime { 0 }
    decision_making_timeline { 0 }
    next_steps { 0 }
    viability_status { 0 }
    viability_desc { 0 }
    fa_epg { 0 }
    fa_region { 0 }
    fa_member_status { 0 }
    usda_region { 0 }
    state_association { 0 }
    relationship_mgr { 0 }
    address_status_id { 0 }
    last_geocode_date_key { 0 }
    tamu_geo_match_type_id { 0 }
    smarty_geo_match_type_id { 0 }
    pt_geo_match_type_id { 0 }
    latitude { Faker::Address.latitude }
    longitude { Faker::Address.longitude }
    tamu_latitude { latitude }
    tamu_longitude { longitude }
    pt_latitude { latitude }
    pt_longitude { longitude }
    time_zone { '' }
    utc_offset { 0 }
    dst { 0 }
    geocluster_id { 0 }
    future7 { 0 }
    source_id { 0 }
    added_by { 0 }
    last_update_by { 0 }
    census_block { 0 }
    census_block_group { 0 }
    census_tract { 0 }
    status_id { 1 }
    phone_public_help { '' }
    fb_url { '' }
    fb_agency_locator_url { '' }
    fb_volunteer_url { '' }
    fb_donate_url { '' }
    fb_food_donate_url { '' }
  end
end
