require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Rails/Date:
  Enabled: false
Rails/HttpPositionalArguments:
  Exclude:
    - 'spec/controllers/**/*'
RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'
RSpec/MultipleExpectations:
  Max: 4
Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/*'
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
