AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a S3 bucket, Cloudfront distribution used for static web hosting.
Parameters:
  Name:
    Type: String
    Description: A friendly name for this Cloudfront distribution.
    Default: freshtrak-ui
  Stage:
    Type: String
    Description: Deployment stage
    AllowedValues:
      - beta
    Default: beta
Resources:
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: http2
        Origins:
          - DomainName: !Sub "${S3WebsiteBucket}.s3.amazonaws.com"
            Id: !Sub "${Stage}-${Name}-Origin"
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: true
        Comment: !Sub "A Cloudfront distribution for ${Name}-${Stage}"
        CustomErrorResponses:
          - ResponseCode: 200
            ErrorCode: 404
            ResponsePagePath: "/index.html"
          - ResponseCode: 200
            ErrorCode: 403
            ResponsePagePath: "/index.html"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          Compress: true
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: !Sub "${Stage}-${Name}-Origin"
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
  S3WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
Outputs:
  S3WebsiteBucketWebsiteURL:
    Description: The S3 bucket used for static web hosting
    Value: !Sub "${S3WebsiteBucket.WebsiteURL}"
  S3WebsiteBucketName:
    Description: Name of the S3 bucket used for static web hosting
    Value: !Ref S3WebsiteBucket
    Export:
      Name: !Sub "${Name}-S3WebsiteBucket"
  CloudfrontDistributionID:
    Description: Name of the cloudfront distribution.
    Value: !Ref CloudfrontDistribution
    Export:
      Name: !Sub "${Name}-CloudfrontDistribution"
