name: CI

on: [push]

jobs:
  test-pantry-finder-api:
    name: Run Unit Tests For Pantry Finder API
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        volumes:
          - "/var/run/mysqld:/var/run/mysqld"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: pantry-finder-api/vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('pantry-finder-api/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
      - name: Setup and Run Tests
        env:
          DB_HOST: 127.0.0.1
          JETS_ENV: test
        run: |
          cd pantry-finder-api
          bundle install --jobs 4 --retry 3
          bin/setup_dev_db
          bundle exec rspec
